// Generated by tools/help-catalog.mjs from docs/PACKS.md. Don't edit: change the docs, then run it again.
export const PACKS = [
  {
    "folder": "help_bp",
    "topic": "help",
    "name": "Realm Help",
    "summary": "One help page for every realm command: how each feature works, and each command with its usage.",
    "steps": [
      {
        "text": "Run §e/realm:help§r. A §lRealm help§r menu lists every feature installed on this realm, with its commands under its name.",
        "ops": false
      },
      {
        "text": "Tap §lAll commands§r to see every command with its usage on one page, or tap a feature for its how-to steps and its commands. §lBack§r returns to the menu.",
        "ops": false
      },
      {
        "text": "Jump straight to a page with §e/realm:help <feature>§r, for example §e/realm:help stash§r or §e/realm:help find§r, or §e/realm:help all§r for every command. Chat autocompletes the feature names.",
        "ops": false
      },
      {
        "text": "§lOperators§r also see the operator-only commands and steps, marked §e(operators)§r.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:help [feature]",
        "ops": false,
        "who": "Everyone",
        "text": "Opens the help menu, or the page for §efeature§r (§eafk§r, §echairs§r, §edurability§r, §efarm§r, §efind§r, §eguard§r, §eharvest§r, §enews§r, §ephantom§r, §erain§r, §esettings§r, §estash§r, §estats§r, §ewelcome§r) or §eall§r"
      }
    ]
  },
  {
    "folder": "settings_bp",
    "topic": "settings",
    "name": "Realm Settings",
    "summary": "Change the packs' settings in game: operators set them for everyone with §e/realm:config§r, and every player picks their own preferences with §e/realm:prefs§r.",
    "steps": [
      {
        "text": "Run §e/realm:prefs§r to open §lMy preferences§r: one form with your own choices from every installed pack, such as turning off durability warnings, phantoms or the rain extras for yourself, what sneak-tapping a chest does, and whether chat announces you going AFK. Change what you like and tap §lSave§r. Chat confirms each change, for example §eSaved: Phantom Opt-out, Turn off phantoms for me: on§r.",
        "ops": false
      },
      {
        "text": "Your choices are remembered. §e/realm:durability§r, §e/realm:phantoms§r and §e/realm:rain§r flip the same switches as the form.",
        "ops": false
      },
      {
        "text": "§lOperators:§r run §e/realm:config§r, or use any item renamed §eRealm Settings§r on an anvil (a stick works). Pick a pack, change its settings (switches, sliders and lists) and tap §lSave§r. They apply right away for everyone, and chat confirms each one. A setting marked §eneeds a world restart§r can only be changed in the pack's §econfig.js§r.",
        "ops": true
      },
      {
        "text": "§lOperators:§r §lReset a pack to defaults§r, at the bottom of the menu, puts one pack's settings back to its §econfig.js§r values after asking. Players' own preferences are kept.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:prefs",
        "ops": false,
        "who": "Everyone",
        "text": "Opens §lMy preferences§r: your own choices from every installed pack, in one form"
      },
      {
        "usage": "/realm:config",
        "ops": true,
        "who": "Ops",
        "text": "Opens §lRealm Settings§r: every installed pack's settings for everyone, then §lReset a pack to defaults§r. Using an item named §eRealm Settings§r opens it too (§eitemName§r)"
      }
    ]
  },
  {
    "folder": "welcome_bp",
    "topic": "welcome",
    "name": "Welcome Message",
    "summary": "Shows a popup when a player joins the Realm. Operators can edit the popup in-game.",
    "steps": [
      {
        "text": "Join the realm. The welcome popup appears after about 2 seconds; tap its button (§eLet's go!§r by default) to close it.",
        "ops": false
      },
      {
        "text": "Run §e/realm:welcome§r any time to see it again. Don't want the popup when you join? Turn off §lShow me the welcome popup when I join§r in §e/realm:prefs§r.",
        "ops": false
      },
      {
        "text": "§lOperators:§r run §e/realm:welcome_edit§r, change the title, body or button text and the switches, then submit. Players see the new text on their next join (with \"show once\" on, each player sees it one more time, unless you turn off \"Show it again to players who've seen it\" for a typo fix). §e/realm:welcome_reset§r asks first, then goes back to the pack's default text.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:welcome",
        "ops": false,
        "who": "Everyone",
        "text": "Shows the welcome message to yourself (preview). Ignores §eshowOnce§r"
      },
      {
        "usage": "/realm:welcome_edit",
        "ops": true,
        "who": "Ops",
        "text": "Opens an editor: title, body, button text, and toggles for show once, chat copy, big on-screen title and \"Show it again to players who've seen it\" (on by default; turn it off for a quiet fix). If chat or the inventory stays open, it retries for about 20 s and then says so once"
      },
      {
        "usage": "/realm:welcome_reset",
        "ops": true,
        "who": "Ops",
        "text": "Asks §eReset the welcome message?§r first, then discards in-game edits and goes back to the §econfig.js§r defaults"
      }
    ]
  },
  {
    "folder": "durability_bp",
    "topic": "durability",
    "name": "Low Durability Warning",
    "summary": "Warns players before a tool, weapon or armor piece breaks.",
    "steps": [
      {
        "text": "Nothing to set up: hold or wear any tool, weapon or armor piece. At §l10%§r durability left a yellow warning appears above the hotbar with a soft chime; at §l3%§r a red \"about to break!\" warning, an anvil sound and the same line in chat.",
        "ops": false
      },
      {
        "text": "Repair the item (Mending, an anvil) or swap it before it breaks. A repaired item warns again the next time it runs low.",
        "ops": false
      },
      {
        "text": "Don't want the warnings? Run §e/realm:durability§r to turn them off for yourself; run it again to turn them back on. The same switch is in §e/realm:prefs§r. The choice is remembered.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:durability",
        "ops": false,
        "who": "Everyone",
        "text": "Turns warnings off or on §lfor yourself§r. Remembered between sessions. Turning them off says §eRun /realm:durability again to turn them back on.§r"
      }
    ]
  },
  {
    "folder": "afk_bp",
    "topic": "afk",
    "name": "AFK + Smart Sleep",
    "summary": "Marks idle players as AFK, and skips the night without waiting for them.",
    "steps": [
      {
        "text": "§lGoing AFK:§r just stop playing. After 5 minutes your name shows §e[AFK]§r and chat says so. To go AFK right away (so the night can be skipped without you), run §e/realm:afk§r.",
        "ops": false
      },
      {
        "text": "§lComing back:§r move or look around. Chat says you're back and, after 30 seconds or more, how many minutes you were marked AFK. Rather chat didn't announce you? Turn off §lTell chat when I go AFK or come back§r in §e/realm:prefs§r.",
        "ops": false
      },
      {
        "text": "§lSkipping the night:§r get in a bed. Players who are AFK, and players in the Nether or the End, aren't waited for. While anyone is in bed, Overworld players see how many are asleep out of how many are needed, above the hotbar, and, when only 1 to 3 counted players are still up, who they are (§e🛏 1/2 sleeping · awake: Sam§r). Once everyone needed is in bed, it's morning within about 8 seconds, and rain or thunder stops.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:afk",
        "ops": false,
        "who": "Everyone",
        "text": "Marks you AFK right away. Anything you do in the next 3 seconds (closing chat, the camera settling) is ignored. After that, move to come back. With announcements off (§eannounce§r, or yours in §e/realm:prefs§r), only you get a confirmation"
      }
    ]
  },
  {
    "folder": "stats_bp",
    "topic": "stats",
    "name": "Stats & Leaderboards",
    "summary": "Tracks player stats as scoreboards, with leaderboard menus and an optional sidebar.",
    "steps": [
      {
        "text": "Play: stats count on their own (playtime and distance, except while AFK; deaths; mob and player kills; blocks mined and placed; elytra distance; joins).",
        "ops": false
      },
      {
        "text": "Run §e/realm:stats§r and pick §lMy stats§r to see every stat, with your rank (§e#2 of 7§r) in each one you've scored in, and the date you first joined (UTC), or §lLeaderboards§r and a stat to see the top 10.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:stats_sidebar <stat>§r shows one stat on everyone's sidebar. Use a stat ID (§eplaytime§r, §edeaths§r, §emobkills§r, §epvpkills§r, §emined§r, §eplaced§r, §etravelled§r, §eflown§r, §ejoins§r), for example §e/realm:stats_sidebar travelled§r, §ecycle§r to rotate through all of them every 30 seconds, or §eoff§r.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:stats",
        "ops": false,
        "who": "Everyone",
        "text": "Opens §lRealm Stats§r: §lMy stats§r (every stat with your rank §e#2 of 7§r, plus first-joined date) or §lLeaderboards§r (pick a stat to see the top 10, §eleaderboardSize§r, with your own position underneath if you're outside it)"
      },
      {
        "usage": "/realm:stats_sidebar <stat>",
        "ops": true,
        "who": "Ops",
        "text": "Shows a stat on everyone's sidebar. §e<stat>§r is a stat ID, §l§ecycle§r§r (rotates through every stat every 30 seconds, §esidebarCycleSeconds§r) or §l§eoff§r§r"
      }
    ]
  },
  {
    "folder": "news_bp",
    "topic": "news",
    "name": "Realm News & Tips",
    "summary": "A news popup that operators edit in-game, a \"welcome back\" notice, and rotating chat tips.",
    "steps": [
      {
        "text": "When there's news, it pops up about 5 seconds after you join, after the welcome popup. Tap §eGot it§r to close it. If you're online when it's posted, chat says §e📰 Realm news updated. Run /realm:news to read it.§r",
        "ops": false
      },
      {
        "text": "Missed it, or want to read it again? Run §e/realm:news§r.",
        "ops": false
      },
      {
        "text": "Tips appear in chat every 20 minutes while someone is online, starting with §e[Tip]§r.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:news_edit§r writes the news. Leave \"Pop up for everyone on their next join\" on to announce it, or turn it off for a quiet fix such as a typo. §e/realm:news_tips§r adds, edits or deletes tips, posts the next one now, changes how often they're posted (5 to 120 minutes) or turns them off.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:news",
        "ops": false,
        "who": "Everyone",
        "text": "Shows the current news, which also counts as having seen its popup"
      },
      {
        "usage": "/realm:news_edit",
        "ops": true,
        "who": "Ops",
        "text": "Editor: title, body, and the \"pop up on next join\" toggle. If chat stays open for about 20 s, it says it couldn't open"
      },
      {
        "usage": "/realm:news_tips",
        "ops": true,
        "who": "Ops",
        "text": "Tips menu: §l+ Add a tip§r, §lSettings§r (on/off, interval 5–120 min in steps of 5), §lPost the next tip now§r, or tap a tip to edit or delete it"
      }
    ]
  },
  {
    "folder": "guard_bp",
    "topic": "guard",
    "name": "Creeper Guard",
    "summary": "Creepers still hurt, but their explosions break no blocks, so nobody comes home to a crater. TNT is left alone.",
    "steps": [
      {
        "text": "Nothing to set up: a creeper that explodes still damages and knocks back players and mobs, but the ground and your builds stay intact.",
        "ops": false
      },
      {
        "text": "Run §e/realm:guard§r to see the mode, which blasts are covered and any protected zones.",
        "ops": false
      },
      {
        "text": "§lOperators:§r to keep creeper craters in the wild and protect only bases, set the mode to §ezones§r in §e/realm:config§r (or §emode§r in §econfig.js§r), then stand in a base and run §e/realm:guard_add <name> [radius]§r (for example §e/realm:guard_add home 64§r). §e/realm:guard_remove <name>§r removes a zone.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:guard",
        "ops": false,
        "who": "Everyone",
        "text": "Shows whether the spot you're standing on is protected (and by which zone), then the mode, the covered blast sources and the zones"
      },
      {
        "usage": "/realm:guard_add <name> [radius]",
        "ops": true,
        "who": "Ops",
        "text": "Protects a sphere around you, §eradius§r 8–256 blocks (default 64, §edefaultRadius§r). Names use letters, digits, §e_§r and §e-§r, up to 24, and must be unique whatever their case (§ehome§r and §eHome§r are the same zone). Only matters in §ezones§r mode"
      },
      {
        "usage": "/realm:guard_remove <name>",
        "ops": true,
        "who": "Ops",
        "text": "Removes a zone (any case)"
      }
    ]
  },
  {
    "folder": "phantom_bp",
    "topic": "phantom",
    "name": "Phantom Opt-out",
    "summary": "Lets each player turn phantoms off for themselves. Phantoms come from not sleeping, and with smart sleep the night can be skipped without everyone in bed, so some players never need to sleep.",
    "steps": [
      {
        "text": "Run §e/realm:phantoms§r, or turn on §lTurn off phantoms for me§r in §e/realm:prefs§r. Chat says §ePhantoms off for you. Run it again to turn them back on.§r The choice is remembered.",
        "ops": false
      },
      {
        "text": "Phantoms that spawn for you now vanish the moment they appear, with no drops. Everyone else's phantoms are untouched.",
        "ops": false
      },
      {
        "text": "Run §e/realm:phantoms§r again to get them back (for phantom membranes, say).",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:phantoms",
        "ops": false,
        "who": "Everyone",
        "text": "Turns phantoms off or on §lfor yourself§r. Remembered between sessions"
      }
    ]
  },
  {
    "folder": "harvest_bp",
    "topic": "harvest",
    "name": "Right-click Harvest",
    "summary": "Tap a ripe crop to harvest it and replant it in one go, so fields never need re-seeding.",
    "steps": [
      {
        "text": "Tap (use) a fully grown crop with an empty hand or a hoe. It pops its normal drops and goes back to a seedling, with the break sound.",
        "ops": false
      },
      {
        "text": "Unripe crops behave as in vanilla, and so does anything else in your hand: seeds still plant, bone meal still grows.",
        "ops": false
      },
      {
        "text": "Sneak while tapping to skip the harvest for that tap.",
        "ops": false
      }
    ],
    "commands": []
  },
  {
    "folder": "farm_bp",
    "topic": "farm",
    "name": "Farm Loader",
    "summary": "Keeps named farms loaded with Bedrock ticking areas, so crops grow, furnaces smelt and redstone runs while everyone is elsewhere.",
    "steps": [
      {
        "text": "Run §e/realm:farm§r to see which farms are kept loaded: name, dimension, coordinates, size, who added it and when.",
        "ops": false
      },
      {
        "text": "§lOperators:§r stand in the middle of a farm and run §e/realm:farm_add <name> [radius]§r, for example §e/realm:farm_add kelp 2§r. The chunks within that many chunks of you stay loaded, and chat confirms §eFarm \"kelp\" stays loaded (radius 2 chunks, 3/10 used)§r.",
        "ops": true
      },
      {
        "text": "§lOperators:§r §e/realm:farm_remove <name>§r stops keeping it loaded, or tap §lRemove§r next to it in §e/realm:farm§r; the menu comes back afterwards, so you can remove another.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:farm",
        "ops": false,
        "who": "Everyone",
        "text": "Lists the loaded farms. Operators also get a §lRemove§r button for each"
      },
      {
        "usage": "/realm:farm_add <name> [radius]",
        "ops": true,
        "who": "Ops (everyone if §eeveryoneCanAdd§r)",
        "text": "Adds a ticking area centered on you, §eradius§r 1–4 chunks (default 2, §edefaultRadius§r). Names use letters, digits, §e_§r and §e-§r, up to 24, and must be unique"
      },
      {
        "usage": "/realm:farm_remove <name>",
        "ops": true,
        "who": "Ops (everyone if §eeveryoneCanAdd§r)",
        "text": "Stops keeping the farm loaded and removes it from the list"
      }
    ]
  },
  {
    "folder": "stash_bp",
    "topic": "stash",
    "name": "Quick Stack & Sort",
    "summary": "Sneak-tap any chest, barrel or shulker box for a menu: sort it, quick stack into the storage that already holds each item (like Terraria), or sort your inventory.",
    "steps": [
      {
        "text": "§lOpen the menu:§r sneak and tap a chest, trapped chest, copper chest, barrel, shulker box or ender chest with an empty hand, or holding a tool, weapon or armor. It doesn't open; a §lQuick Stack & Sort§r menu does, with three buttons:\n  • §lSort this chest§r (or barrel, shulker box…): its stacks merge and sort, and the bar above the hotbar says §eSorted 31 stacks§r.\n  • §lQuick stack my inventory:§r the same as §e/realm:stash§r, below.\n  • §lSort my inventory:§r the same as §e/realm:sort§r, below.",
        "ops": false
      },
      {
        "text": "§lQuick stack:§r stand near your storage and run §e/realm:stash§r. Every item in your main inventory goes into a chest, copper chest or barrel within 8 blocks that already holds the same item. Your gear, shulker boxes, bundles, totems, maps and compasses stay with you. The bar says §eStashed 143 items into 3 chests§r, and each container that got something sparkles.",
        "ops": false
      },
      {
        "text": "§lSort your inventory:§r run §e/realm:sort§r. Your main inventory is sorted; the hotbar stays as it is.",
        "ops": false
      },
      {
        "text": "§lYour way:§r in §e/realm:prefs§r, choose what sneak-tapping a container does for you (§emenu§r, §esort§r right away, or §eoff§r so it just opens), and whether sorting your inventory includes your hotbar.",
        "ops": false
      },
      {
        "text": "§lHelp:§r run §e/realm:stash_help§r for a page that explains the menu and every command with its usage. §e/help realm:stash§r and §e/help realm:sort§r also describe them.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:stash",
        "ops": false,
        "who": "Everyone",
        "text": "Quick stack: puts your main inventory into chests and barrels within 8 blocks that already hold the same items, keeping your gear and carried items. Same as the menu's §lQuick stack my inventory§r"
      },
      {
        "usage": "/realm:sort",
        "ops": false,
        "who": "Everyone",
        "text": "Sorts your inventory, slots 9–35. The hotbar is untouched, unless you turned that on in §e/realm:prefs§r (default off, §esortHotbar§r). Same as the menu's §lSort my inventory§r"
      },
      {
        "usage": "/realm:stash_help",
        "ops": false,
        "who": "Everyone",
        "text": "Opens the help page: the sneak-tap menu, then each command with its usage and what it never touches"
      }
    ]
  },
  {
    "folder": "find_bp",
    "topic": "find",
    "name": "Chest Finder",
    "summary": "Answers \"which chest has the iron?\" for a shared base: it remembers what each container held the last time anyone opened it, and points you to it.",
    "steps": [
      {
        "text": "Open chests as usual. The pack quietly remembers what's in them.",
        "ops": false
      },
      {
        "text": "Run §e/realm:find iron§r, or just §e/realm:find§r while holding the item. A menu lists the containers that have it, nearest first, for example §eChest · 23 Iron Ingot§r with §e35 blocks NE · seen 2h ago§r under it.",
        "ops": false
      },
      {
        "text": "Tap a result: a column of particles marks that container for 10 seconds. Only you see it, and chat gives its coordinates.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:find [item]",
        "ops": false,
        "who": "Everyone",
        "text": "Searches remembered and nearby containers for §eitem§r (any part of an item id), or for the item in your hand if you leave it out"
      }
    ]
  },
  {
    "folder": "chairs_bp",
    "topic": "chairs",
    "name": "Chairs",
    "summary": "Sit on any stair or bottom slab, which makes the furnished houses on mc.nish.software feel lived in.",
    "steps": [
      {
        "text": "Tap a stair or a bottom slab with an empty hand, standing within 2.5 blocks of it. You sit on it, facing away from the stair's back.",
        "ops": false
      },
      {
        "text": "Sneak to stand up (on touch screens, the dismount button). The bar above the hotbar reminds you when you sit.",
        "ops": false
      },
      {
        "text": "Run §e/realm:sit§r to sit down right where you stand.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:sit",
        "ops": false,
        "who": "Everyone",
        "text": "Sits you down where you stand (on the ground). Sneak to stand up"
      }
    ]
  },
  {
    "folder": "rain_bp",
    "topic": "rain",
    "name": "Rain Extras",
    "summary": "Storm fog, ground mist and drips under leaves and roof edges, for the Realistic Rain resource pack. A §lstandalone§r behavior pack: it runs next to the Realm Bundle, not inside it.",
    "steps": [
      {
        "text": "When it rains, water drips from the leaves of trees and from roof edges near you, and keeps dripping for a while after the rain stops.",
        "ops": false
      },
      {
        "text": "In a thunderstorm, the fog rolls in thicker and darker over about 12 seconds, and low mist drifts along the ground around you when you're outdoors. Both clear the same way when the storm passes.",
        "ops": false
      },
      {
        "text": "Run §e/realm:rain§r, or use the same switch in §e/realm:prefs§r, to turn these extras off for yourself, on a slower device for example. Chat says §eRain extras off for you (storm fog, mist and drips). Run it again to turn them back on.§r The choice is remembered.",
        "ops": false
      },
      {
        "text": "§lOperators:§r add Rain Extras under §lBehavior Packs§r, next to the Realm Bundle (it's never part of the bundle), and add Realistic Rain under §lResource Packs§r at the top of the list. The storm fogs and particles come from Realistic Rain, so without it nothing shows.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:rain",
        "ops": false,
        "who": "Everyone",
        "text": "Turns storm fog, ground mist and drips off or on §lfor yourself§r (on by default, §edefaultOff§r). Remembered between sessions"
      }
    ]
  }
];
