// Generated by tools/help-catalog.mjs from docs/PACKS.md. Don't edit: change the docs, then run it again.
export const PACKS = [
  {
    "folder": "help_bp",
    "topic": "help",
    "name": "Realm Help",
    "summary": "One help page for every realm command: how each feature works, and each command with its usage.",
    "steps": [
      {
        "text": "Run §e/realm:help§r. A §lRealm help§r menu lists every feature installed on this realm, with its commands under its name.",
        "ops": false
      },
      {
        "text": "Tap §lAll commands§r to see every command with its usage on one page, or tap a feature for its how-to steps and its commands. §lBack§r returns to the menu.",
        "ops": false
      },
      {
        "text": "Jump straight to a page with §e/realm:help <feature>§r, for example §e/realm:help stash§r or §e/realm:help find§r, or §e/realm:help all§r for every command. Chat autocompletes the feature names.",
        "ops": false
      },
      {
        "text": "§lOperators§r also see the operator-only commands and steps, marked §e(operators)§r.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:help [feature]",
        "ops": false,
        "who": "Everyone",
        "text": "Opens the help menu, or the page for §efeature§r (§eafk§r, §echairs§r, §edurability§r, §efarm§r, §efind§r, §eguard§r, §eharvest§r, §enews§r, §ephantom§r, §erain§r, §esettings§r, §estash§r, §estats§r, §ewelcome§r) or §eall§r"
      }
    ]
  },
  {
    "folder": "settings_bp",
    "topic": "settings",
    "name": "Realm Settings",
    "summary": "Change the packs' settings in game: operators set them for everyone with §e/realm:config§r, and every player picks their own preferences with §e/realm:prefs§r.",
    "steps": [
      {
        "text": "Run §e/realm:prefs§r to open §lMy preferences§r: one form with your own choices from every installed pack, such as whether you get durability warnings, phantoms or the rain extras, what sneak-tapping a chest does, and whether chat announces you going AFK. Every switch is named for what it does: on means §lEnabled§r. Change what you like and tap §lSave§r. A summary pops up with how many changes were saved and each one as before -> after, for example §e1 change saved§r and §ePhantom Opt-out > Phantoms near me: Enabled -> Disabled§r (chat gets the same). Tap §lBack to my preferences§r to change more, or §lDone§r.",
        "ops": false
      },
      {
        "text": "Your choices are remembered. §e/realm:durability§r, §e/realm:phantoms§r and §e/realm:rain§r flip the same switches as the form.",
        "ops": false
      },
      {
        "text": "§lOperators:§r run §e/realm:config§r, or use any item renamed §eRealm Settings§r on an anvil (a stick works). Pick a pack, change its settings (switches, sliders and lists) and tap §lSave§r. They apply right away for everyone. A summary pops up with how many changes were saved and each one as before -> after, such as §eStorm wind volume: 70% -> 50%§r; tap §lBack to Realm Settings§r for another pack, or §lDone§r. A setting shown as text with §e(change in config.js, then restart the world)§r can only be changed there.",
        "ops": true
      },
      {
        "text": "§lOperators:§r §lReset a pack to defaults§r, at the bottom of the menu, puts one pack's settings back to its §econfig.js§r values after asking. Players' own preferences are kept.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:prefs",
        "ops": false,
        "who": "Everyone",
        "text": "Opens §lMy preferences§r: your own choices from every installed pack, in one form"
      },
      {
        "usage": "/realm:config",
        "ops": true,
        "who": "Ops",
        "text": "Opens §lRealm Settings§r: every installed pack's settings for everyone, then §lReset a pack to defaults§r. Using an item named §eRealm Settings§r opens it too (§eitemName§r)"
      }
    ]
  },
  {
    "folder": "welcome_bp",
    "topic": "welcome",
    "name": "Welcome Message",
    "summary": "Shows a popup when a player joins the Realm. Operators can edit the popup in-game.",
    "steps": [
      {
        "text": "Join the realm. The welcome popup appears after about 2 seconds; tap its button (§eLet's go!§r by default) to close it.",
        "ops": false
      },
      {
        "text": "Run §e/realm:welcome§r any time to see it again. Don't want the popup when you join? Disable §lWelcome popup when I join§r in §e/realm:prefs§r.",
        "ops": false
      },
      {
        "text": "§lOperators:§r run §e/realm:welcome_edit§r, change the title, body or button text and the switches, then submit. Players see the new text on their next join (with \"show once\" on, each player sees it one more time, unless you turn off \"Show it again to players who've seen it\" for a typo fix). §e/realm:welcome_reset§r asks first, then goes back to the pack's default text.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:welcome",
        "ops": false,
        "who": "Everyone",
        "text": "Shows the welcome message to yourself (preview). Ignores §eshowOnce§r"
      },
      {
        "usage": "/realm:welcome_edit",
        "ops": true,
        "who": "Ops",
        "text": "Opens an editor: title, body, button text, and toggles for show once, chat copy, big on-screen title and \"Show it again to players who've seen it\" (on by default; turn it off for a quiet fix). If chat or the inventory stays open, it retries for about 20 s and then says so once"
      },
      {
        "usage": "/realm:welcome_reset",
        "ops": true,
        "who": "Ops",
        "text": "Asks §eReset the welcome message?§r first, then discards in-game edits and goes back to the §econfig.js§r defaults"
      }
    ]
  },
  {
    "folder": "durability_bp",
    "topic": "durability",
    "name": "Low Durability Warning",
    "summary": "Warns players before a tool, weapon or armor piece breaks.",
    "steps": [
      {
        "text": "Nothing to set up: hold or wear any tool, weapon or armor piece. At §l10%§r durability left a yellow warning appears above the hotbar with a soft chime; at §l3%§r a red \"about to break!\" warning, an anvil sound and the same line in chat.",
        "ops": false
      },
      {
        "text": "Repair the item (Mending, an anvil) or swap it before it breaks. A repaired item warns again the next time it runs low.",
        "ops": false
      },
      {
        "text": "Don't want the warnings? Run §e/realm:durability§r to turn them off for yourself; run it again to turn them back on. The same switch is in §e/realm:prefs§r. The choice is remembered.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:durability",
        "ops": false,
        "who": "Everyone",
        "text": "Enables or disables warnings §lfor yourself§r. Remembered between sessions. Chat says §eLow-durability warnings: Disabled. Run /realm:durability again to enable them.§r"
      }
    ]
  },
  {
    "folder": "afk_bp",
    "topic": "afk",
    "name": "AFK + Smart Sleep",
    "summary": "Marks idle players as AFK, and skips the night without waiting for them.",
    "steps": [
      {
        "text": "§lGoing AFK:§r just stop playing. After 5 minutes your name shows §e[AFK]§r and chat says so. To go AFK right away (so the night can be skipped without you), run §e/realm:afk§r.",
        "ops": false
      },
      {
        "text": "§lComing back:§r move or look around. Chat says you're back and, after 30 seconds or more, how many minutes you were marked AFK. Rather chat didn't announce you? Disable §lAnnounce when I go AFK§r in §e/realm:prefs§r.",
        "ops": false
      },
      {
        "text": "§lSkipping the night:§r get in a bed. Players who are AFK, and players in the Nether or the End, aren't waited for. While anyone is in bed, Overworld players see how many are asleep out of how many are needed, above the hotbar, and, when only 1 to 3 counted players are still up, who they are (§eZzz 1/2 sleeping - awake: Sam§r). Once everyone needed is in bed, it's morning within about 8 seconds, and rain or thunder stops.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:afk",
        "ops": false,
        "who": "Everyone",
        "text": "Marks you AFK right away. Anything you do in the next 3 seconds (closing chat, the camera settling) is ignored. After that, move to come back. With announcements off (§eannounce§r, or yours in §e/realm:prefs§r), only you get a confirmation"
      }
    ]
  },
  {
    "folder": "stats_bp",
    "topic": "stats",
    "name": "Stats & Leaderboards",
    "summary": "Tracks player stats as scoreboards, with leaderboard menus and an optional sidebar.",
    "steps": [
      {
        "text": "Play: stats count on their own (playtime and distance, except while AFK; deaths; mob and player kills; blocks mined and placed; elytra distance; joins).",
        "ops": false
      },
      {
        "text": "Run §e/realm:stats§r and pick §lMy stats§r to see every stat, with your rank (§e#2 of 7§r) in each one you've scored in, and the date you first joined (UTC), or §lLeaderboards§r and a stat to see the top 10.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:stats_sidebar <stat>§r shows one stat on everyone's sidebar. Use a stat ID (§eplaytime§r, §edeaths§r, §emobkills§r, §epvpkills§r, §emined§r, §eplaced§r, §etravelled§r, §eflown§r, §ejoins§r), for example §e/realm:stats_sidebar travelled§r, §ecycle§r to rotate through all of them every 30 seconds, or §eoff§r.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:stats",
        "ops": false,
        "who": "Everyone",
        "text": "Opens §lRealm Stats§r: §lMy stats§r (every stat with your rank §e#2 of 7§r, plus first-joined date) or §lLeaderboards§r (pick a stat to see the top 10, §eleaderboardSize§r, with your own position underneath if you're outside it)"
      },
      {
        "usage": "/realm:stats_sidebar <stat>",
        "ops": true,
        "who": "Ops",
        "text": "Shows a stat on everyone's sidebar. §e<stat>§r is a stat ID, §l§ecycle§r§r (rotates through every stat every 30 seconds, §esidebarCycleSeconds§r) or §l§eoff§r§r"
      }
    ]
  },
  {
    "folder": "news_bp",
    "topic": "news",
    "name": "Realm News & Tips",
    "summary": "A news popup that operators edit in-game, a \"welcome back\" notice, and rotating chat tips.",
    "steps": [
      {
        "text": "When there's news, it pops up about 5 seconds after you join, after the welcome popup. Tap §eGot it§r to close it. If you're online when it's posted, chat says §eRealm news updated. Run /realm:news to read it.§r",
        "ops": false
      },
      {
        "text": "Missed it, or want to read it again? Run §e/realm:news§r.",
        "ops": false
      },
      {
        "text": "Tips appear in chat every 20 minutes while someone is online, starting with §e[Tip]§r.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:news_edit§r writes the news. Minecraft's text boxes hold only 100 characters each, so the body is split over at least 10 boxes (1,000 characters) that are joined in order with nothing between them; type §e\\n§r for a new line. Easier for a long message: paste it into chat as §e/realm:news_body \"<text>\"§r, with §e|§r for each new line, and the editor opens with every box filled in; check the title and tap §lSave§r. Chat has a length limit too, so for a message longer than one paste, paste it in parts: the first part with §e/realm:news_body§r (close the editor that opens, or just keep chat open), each next part with §e/realm:news_add \"<text>\"§r, then run §e/realm:news_edit§r to check and save the whole draft. Parts are joined exactly as pasted, so end a part on a space or start the next one with one. Leave \"Pop up for everyone on their next join\" on to announce it, or turn it off for a quiet fix such as a typo. §e/realm:news_tips§r adds, edits or deletes tips, posts the next one now, changes how often they're posted (5 to 120 minutes) or turns them off.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:news",
        "ops": false,
        "who": "Everyone",
        "text": "Shows the current news, which also counts as having seen its popup"
      },
      {
        "usage": "/realm:news_edit",
        "ops": true,
        "who": "Ops",
        "text": "Editor: title, the body in 100-character parts (at least 10, joined in order), and the \"pop up on next join\" toggle. If you have a draft from §e/realm:news_body§r or §e/realm:news_add§r, it shows the draft instead of the saved news, with a toggle to discard it. §lSave§r saves the news and clears the draft; closing the editor keeps the draft. If chat stays open for about 20 s, it says it couldn't open"
      },
      {
        "usage": "/realm:news_body \"<text>\"",
        "ops": true,
        "who": "Ops",
        "text": "Starts a news draft from pasted text (chat takes more than a form's 100-character boxes) and opens the editor with it split over the boxes. Put the text in double quotes, use `"
      },
      {
        "usage": "/realm:news_add \"<text>\"",
        "ops": true,
        "who": "Ops",
        "text": "Adds pasted text to the end of your draft, for news longer than chat lets you paste at once. Doesn't open the editor; it says how long the draft is now (10,000 characters at most). `"
      },
      {
        "usage": "/realm:news_tips",
        "ops": true,
        "who": "Ops",
        "text": "Tips menu: §l+ Add a tip§r, §lSettings§r (on/off, interval 5-120 min in steps of 5), §lPost the next tip now§r, or tap a tip to edit or delete it"
      }
    ]
  },
  {
    "folder": "guard_bp",
    "topic": "guard",
    "name": "Creeper Guard",
    "summary": "Creepers still hurt, but their explosions break no blocks, so nobody comes home to a crater. TNT is left alone.",
    "steps": [
      {
        "text": "Nothing to set up: a creeper that explodes still damages and knocks back players and mobs, but the ground and your builds stay intact.",
        "ops": false
      },
      {
        "text": "Run §e/realm:guard§r to see the mode, which blasts are covered and any protected zones.",
        "ops": false
      },
      {
        "text": "§lOperators:§r to keep creeper craters in the wild and protect only bases, set the mode to §ezones§r in §e/realm:config§r (or §emode§r in §econfig.js§r), then stand in a base and run §e/realm:guard_add <name> [radius]§r (for example §e/realm:guard_add home 64§r). §e/realm:guard_remove <name>§r removes a zone.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:guard",
        "ops": false,
        "who": "Everyone",
        "text": "Shows whether the spot you're standing on is protected (and by which zone), then the mode, the covered blast sources and the zones"
      },
      {
        "usage": "/realm:guard_add <name> [radius]",
        "ops": true,
        "who": "Ops",
        "text": "Protects a sphere around you, §eradius§r 8-256 blocks (default 64, §edefaultRadius§r). Names use letters, digits, §e_§r and §e-§r, up to 24, and must be unique whatever their case (§ehome§r and §eHome§r are the same zone). Only matters in §ezones§r mode"
      },
      {
        "usage": "/realm:guard_remove <name>",
        "ops": true,
        "who": "Ops",
        "text": "Removes a zone (any case)"
      }
    ]
  },
  {
    "folder": "phantom_bp",
    "topic": "phantom",
    "name": "Phantom Opt-out",
    "summary": "Lets each player disable phantoms for themselves. Phantoms come from not sleeping, and with smart sleep the night can be skipped without everyone in bed, so some players never need to sleep.",
    "steps": [
      {
        "text": "Run §e/realm:phantoms§r, or disable §lPhantoms near me§r in §e/realm:prefs§r. Chat says §ePhantoms near you: Disabled. Run /realm:phantoms again to enable them.§r The choice is remembered.",
        "ops": false
      },
      {
        "text": "Phantoms that spawn for you now vanish the moment they appear, with no drops. Everyone else's phantoms are untouched.",
        "ops": false
      },
      {
        "text": "Run §e/realm:phantoms§r again to get them back (for phantom membranes, say).",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:phantoms",
        "ops": false,
        "who": "Everyone",
        "text": "Enables or disables phantoms §lfor yourself§r. Remembered between sessions"
      }
    ]
  },
  {
    "folder": "harvest_bp",
    "topic": "harvest",
    "name": "Right-click Harvest",
    "summary": "Tap a ripe crop to harvest it and replant it in one go, so fields never need re-seeding.",
    "steps": [
      {
        "text": "Tap (use) a fully grown crop with an empty hand or a hoe. It pops its normal drops and goes back to a seedling, with the break sound.",
        "ops": false
      },
      {
        "text": "Unripe crops behave as in vanilla, and so does anything else in your hand: seeds still plant, bone meal still grows.",
        "ops": false
      },
      {
        "text": "Sneak while tapping to skip the harvest for that tap.",
        "ops": false
      }
    ],
    "commands": []
  },
  {
    "folder": "farm_bp",
    "topic": "farm",
    "name": "Farm Loader",
    "summary": "Keeps named farms loaded with Bedrock ticking areas, so crops grow, furnaces smelt and redstone runs while everyone is elsewhere.",
    "steps": [
      {
        "text": "Run §e/realm:farm§r to see which farms are kept loaded: name, dimension, coordinates, size, who added it and when.",
        "ops": false
      },
      {
        "text": "§lOperators:§r stand in the middle of a farm and run §e/realm:farm_add <name> [radius]§r, for example §e/realm:farm_add kelp 2§r. The chunks within that many chunks of you stay loaded, and chat confirms §eFarm \"kelp\" stays loaded (radius 2 chunks, 3/10 used)§r.",
        "ops": true
      },
      {
        "text": "§lOperators:§r §e/realm:farm_remove <name>§r stops keeping it loaded, or tap §lRemove§r next to it in §e/realm:farm§r; the menu comes back afterwards, so you can remove another.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:farm",
        "ops": false,
        "who": "Everyone",
        "text": "Lists the loaded farms. Operators also get a §lRemove§r button for each"
      },
      {
        "usage": "/realm:farm_add <name> [radius]",
        "ops": true,
        "who": "Ops (everyone if §eeveryoneCanAdd§r)",
        "text": "Adds a ticking area centered on you, §eradius§r 1-4 chunks (default 2, §edefaultRadius§r). Names use letters, digits, §e_§r and §e-§r, up to 24, and must be unique"
      },
      {
        "usage": "/realm:farm_remove <name>",
        "ops": true,
        "who": "Ops (everyone if §eeveryoneCanAdd§r)",
        "text": "Stops keeping the farm loaded and removes it from the list"
      }
    ]
  },
  {
    "folder": "stash_bp",
    "topic": "stash",
    "name": "Quick Stack & Sort",
    "summary": "Sneak-tap any chest, barrel or shulker box for a menu: sort it, lock it, quick stack into the storage that already holds each item (like Terraria), or sort your inventory.",
    "steps": [
      {
        "text": "§lOpen the menu:§r sneak and tap a chest, trapped chest, copper chest, barrel, shulker box or ender chest with an empty hand, or holding a tool, weapon or armor. It doesn't open; a §lQuick Stack & Sort§r menu does, with these buttons:\n  - §lSort this chest§r (or barrel, shulker box...): its stacks merge and sort, and the bar above the hotbar says §eSorted 31 stacks§r.\n  - §lLock this chest:§r only you can open, sort or break it. Once it's yours, the button reads §lShare or unlock§r: share it with players who are online, stop sharing, or unlock it.\n  - §lQuick stack my inventory:§r the same as §e/realm:stash§r, below.\n  - §lSort my inventory:§r the same as §e/realm:sort§r, below.",
        "ops": false
      },
      {
        "text": "§lQuick stack:§r stand near your storage and run §e/realm:stash§r. Every item in your main inventory goes into a chest, copper chest or barrel within 8 blocks that already holds the same item. Your gear, shulker boxes, bundles, totems, maps and compasses stay with you. The bar says §eStashed 143 items into 3 chests§r, and each container that got something sparkles.",
        "ops": false
      },
      {
        "text": "§lSort your inventory:§r run §e/realm:sort§r. Your main inventory is sorted; the hotbar stays as it is.",
        "ops": false
      },
      {
        "text": "§lYour way:§r in §e/realm:prefs§r, choose what sneak-tapping a container does for you (§emenu§r, §esort§r right away, or §eoff§r so it just opens), and whether sorting your inventory includes your hotbar.",
        "ops": false
      },
      {
        "text": "§lHelp:§r run §e/realm:stash_help§r for a page that explains the menu, chest locks and every command with its usage. §e/help realm:stash§r and §e/help realm:sort§r also describe them.",
        "ops": false
      },
      {
        "text": "§lOperators:§r sneak-tap someone else's locked container for §lRemove the lock (operator)§r. To switch chest locks off for the realm, disable §lChest locks§r in §e/realm:config§r (existing locks are kept for when they're enabled again).",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:stash",
        "ops": false,
        "who": "Everyone",
        "text": "Quick stack: puts your main inventory into chests and barrels within 8 blocks that already hold the same items, keeping your gear and carried items. Same as the menu's §lQuick stack my inventory§r"
      },
      {
        "usage": "/realm:sort",
        "ops": false,
        "who": "Everyone",
        "text": "Sorts your inventory, slots 9-35. The hotbar is untouched, unless you turned that on in §e/realm:prefs§r (default off, §esortHotbar§r). Same as the menu's §lSort my inventory§r"
      },
      {
        "usage": "/realm:stash_help",
        "ops": false,
        "who": "Everyone",
        "text": "Opens the help page: the sneak-tap menu, then each command with its usage and what it never touches"
      }
    ]
  },
  {
    "folder": "find_bp",
    "topic": "find",
    "name": "Chest Finder",
    "summary": "Answers \"which chest has the iron?\" for a shared base: it remembers what each container held the last time anyone opened it, and points you to it.",
    "steps": [
      {
        "text": "Open chests as usual. The pack quietly remembers what's in them.",
        "ops": false
      },
      {
        "text": "Run §e/realm:find iron§r, or just §e/realm:find§r while holding the item. A menu lists the containers that have it, nearest first, for example §eChest - 23 Iron Ingot§r with §e35 blocks NE - seen 2h ago§r under it.",
        "ops": false
      },
      {
        "text": "Tap a result: a column of particles marks that container for 10 seconds. Only you see it, and chat gives its coordinates.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:find [item]",
        "ops": false,
        "who": "Everyone",
        "text": "Searches remembered and nearby containers for §eitem§r (any part of an item id), or for the item in your hand if you leave it out"
      }
    ]
  },
  {
    "folder": "claims_bp",
    "topic": "claims",
    "name": "Land Claims",
    "summary": "Claim the land around your base so other players can't break, place or open anything there. §lOff until an operator enables it§r: until then §e/realm:claim§r only says so and nothing is protected.",
    "steps": [
      {
        "text": "Once an operator has enabled land claims, stand in the middle of your base and run §e/realm:claim§r, then pick §lClaim this land§r. You get 33 x 33 blocks around you (default radius 16, §eradius§r), from the bottom of the world to the top, and green sparkles show its borders.",
        "ops": false
      },
      {
        "text": "Inside it, only you and the players you share it with can break or place blocks, open chests, doors and furnaces, press buttons, pour buckets, or use armor stands and chest minecarts or boats. Anyone else sees §eThis land is claimed by Sam§r.",
        "ops": false
      },
      {
        "text": "§lShare it:§r §e/realm:claim§r -> §lMy claim: 120, -340§r -> §lShare with Alex§r (players online now). The same menu stops sharing, shows its borders or removes the claim.",
        "ops": false
      },
      {
        "text": "§lWhere are the borders?§r §e/realm:claim§r -> §lShow claim borders§r sparkles the edges of every claim near you for 10 seconds. Walking in or out of one says §eEntering Sam's claim§r / §eLeaving Sam's claim§r above the hotbar.",
        "ops": false
      },
      {
        "text": "§lOperators:§r enable it in §e/realm:config§r -> §lLand Claims§r -> §lLand claims§r, and set the claim size and how many each player gets there. §e/realm:claim§r -> §lAll claims (operator)§r lists every claim to remove any of them.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:claim",
        "ops": false,
        "who": "Everyone",
        "text": "Opens the Land Claims menu: claim the land around you (default 33 x 33 blocks, §eradius§r 16), show nearby claim borders, share or remove your claims (default 2 each, §emaxClaims§r); operators also get every claim, to remove any. Only works once an operator has enabled land claims (default disabled, §eenabled§r)"
      }
    ]
  },
  {
    "folder": "death_bp",
    "topic": "death",
    "name": "Death Point",
    "summary": "Tells you where you died once you respawn, and points you back there. The realm keeps inventories on death, so nothing is lying on the ground waiting for you: this is for finding your way back to where you were, say a cave you were exploring or a long trip through the Nether.",
    "steps": [
      {
        "text": "Nothing to set up: when you respawn after dying, chat says §eYou died at 120, 64, -340 in the Overworld.§r",
        "ops": false
      },
      {
        "text": "Run §e/realm:death§r any time to see your last death point again, how far it is from where you stand and in which direction, for example §eIt's 245 blocks to the NE, 12 blocks down.§r",
        "ops": false
      },
      {
        "text": "Don't want the chat message? Disable §lTell me where I died§r in §e/realm:prefs§r. §e/realm:death§r still works.",
        "ops": false
      },
      {
        "text": "If an operator has enabled it, run §e/realm:death_back§r to teleport to your last death point, once per death. It only lands you somewhere safe to stand, and says so when there isn't such a place.",
        "ops": false
      },
      {
        "text": "§lOperators:§r enable §e/realm:death_back§r in §e/realm:config§r -> §lDeath Point§r -> §lTeleport back to the death point (/realm:death_back)§r. The same page turns the respawn message off for everyone.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:death",
        "ops": false,
        "who": "Everyone",
        "text": "Shows your last death point (x, y, z and dimension), with the distance and direction from where you stand, or which dimension it's in"
      },
      {
        "usage": "/realm:death_back",
        "ops": false,
        "who": "Everyone, once an operator enables it",
        "text": "Teleports you to a safe spot at your last death point, once per death (default disabled, §ebackEnabled§r). Refuses with a reason when there's no safe place to stand"
      }
    ]
  },
  {
    "folder": "refill_bp",
    "topic": "refill",
    "name": "Hotbar Refill",
    "summary": "When the stack in your hand runs out, or your tool breaks, the same slot is refilled from your inventory, so you keep building, eating or fighting without opening it.",
    "steps": [
      {
        "text": "Nothing to set up: keep spare stacks and spare tools in your main inventory (above the hotbar). Place your last block, eat your last steak, throw your last snowball or ender pearl, or break your pickaxe, and a matching stack or tool from your inventory moves into that hotbar slot.",
        "ops": false
      },
      {
        "text": "Don't want it? Run §e/realm:refill§r to disable it for yourself; run it again to enable it. The same switch is §lRefill my hotbar§r in §e/realm:prefs§r. The choice is remembered.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:config§r -> §lHotbar Refill§r disables it for the whole realm, stops it replacing broken tools, or changes what new players start with.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:refill",
        "ops": false,
        "who": "Everyone",
        "text": "Enables or disables hotbar refills §lfor yourself§r (default enabled, §edefaultOn§r). Remembered between sessions. Chat says §eHotbar refill: Disabled. Run /realm:refill again to enable it.§r"
      }
    ]
  },
  {
    "folder": "hud_bp",
    "topic": "hud",
    "name": "Coordinates HUD",
    "summary": "Your own coordinates, the direction you're facing and the day and time, on the bar above the hotbar, for players who enable it. Handy for building, mapping and meeting up without opening a map.",
    "steps": [
      {
        "text": "Run §e/realm:hud§r. Above your hotbar you now see §eXYZ 120 64 -340  Facing NE  Day 12 at 6:30 AM§r, updated as you move. Only you see yours.",
        "ops": false
      },
      {
        "text": "Run §e/realm:hud§r again to hide it. The choice is remembered. The same switch is §lCoordinates HUD above my hotbar§r in §e/realm:prefs§r.",
        "ops": false
      },
      {
        "text": "Only want the coordinates? Disable §lHUD shows the day and time§r in §e/realm:prefs§r.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:config§r -> §lCoordinates HUD§r disables it for the whole realm (for servers that play without coordinates), shows it to new players from the start, or switches the facing to 4 directions.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:hud",
        "ops": false,
        "who": "Everyone",
        "text": "Shows or hides your coordinates, facing and the day and time above the hotbar, §lfor yourself§r (default hidden, §edefaultOn§r). Remembered between sessions. Says so when an operator has disabled it for the realm (§eenabled§r)"
      }
    ]
  },
  {
    "folder": "mobhp_bp",
    "topic": "mobhp",
    "name": "Mob Health",
    "summary": "Hit a mob and its name and health show above your hotbar, so you know how close it is to going down.",
    "steps": [
      {
        "text": "Nothing to set up: hit a mob with anything, or shoot it, and the bar above your hotbar shows something like §eZombie  14/20 ||||||||||§r with the bar in color. Only you see it.",
        "ops": false
      },
      {
        "text": "Don't want it? Run §e/realm:mobhp§r to hide it for yourself; run it again to show it. The same switch is §lShow the health of mobs I hit§r in §e/realm:prefs§r. The choice is remembered.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:config§r -> §lMob Health§r disables it for the whole realm, shows players' health too when one player hurts another, changes the bar length, or changes what new players start with.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:mobhp",
        "ops": false,
        "who": "Everyone",
        "text": "Shows or hides the health of mobs you hit, §lfor yourself§r (default shown, §edefaultOn§r). Remembered between sessions. Chat says §eMob health: Disabled. Run /realm:mobhp again to show it.§r"
      }
    ]
  },
  {
    "folder": "elytra_bp",
    "topic": "elytra",
    "name": "Elytra HUD",
    "summary": "While you glide, the bar above the hotbar shows your speed, height, how much durability your elytra has left and how many firework rockets you carry.",
    "steps": [
      {
        "text": "Put on an elytra and glide. Above the hotbar you see something like §e31.4 blocks/s  Y 142  Elytra 87%  Rockets 12§r, updated 4 times a second.",
        "ops": false
      },
      {
        "text": "Don't want it? Run §e/realm:elytra§r, or disable §lElytra HUD while gliding§r in §e/realm:prefs§r. Chat says §eElytra HUD: Disabled. Run /realm:elytra again to enable it.§r The choice is remembered.",
        "ops": false
      },
      {
        "text": "§lOperators:§r to turn it off for everyone, disable §lElytra HUD§r in §e/realm:config§r -> §lElytra HUD§r. The same page sets when durability turns red.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:elytra",
        "ops": false,
        "who": "Everyone",
        "text": "Enables or disables the gliding HUD §lfor yourself§r (enabled by default). Remembered between sessions. Works while the HUD is enabled for the realm (default enabled, §eenabled§r)"
      }
    ]
  },
  {
    "folder": "mail_bp",
    "topic": "mail",
    "name": "Realm Mail",
    "summary": "Write letters to anyone who has played on the realm, online or not. Letters to offline players wait in their inbox, and they're told about them when they join. Letters carry words only: for items, see the Player Mailroom build.",
    "steps": [
      {
        "text": "Run §e/realm:mail§r and pick §lWrite a letter§r. Choose who it's for (everyone who has joined since the pack was added, with §e(online)§r after the ones playing now), type a subject and the letter, and press §lSend§r. Type §e\\n§r in the letter for a new line.",
        "ops": false
      },
      {
        "text": "If they're online, they see §eNew letter from Sam: \"Hello!\". Read it with /realm:mail§r in chat. If not, the letter waits: the next time they join, chat says §eYou have 2 unread letters: /realm:mail§r.",
        "ops": false
      },
      {
        "text": "§lRead your letters:§r §e/realm:mail§r -> §lInbox§r. New letters are marked §e[New]§r. Open one to read it, then §lReply§r or §lDelete§r it. §lDelete all read letters§r clears out the rest.",
        "ops": false
      },
      {
        "text": "§lSee what you sent:§r §e/realm:mail§r -> §lSent§r shows your recent letters and whether each was read yet.",
        "ops": false
      },
      {
        "text": "Don't want the chat line on joining? Disable §lUnread letters notice on join§r in §e/realm:prefs§r.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:config§r -> §lRealm Mail§r sets how many letters an inbox holds, how many are kept in Sent, the wait between letters, and whether players are told about unread letters on joining.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:mail",
        "ops": false,
        "who": "Everyone",
        "text": "Opens Realm Mail: your §lInbox§r (read, reply, delete; default 50 letters each, §einboxLimit§r), §lWrite a letter§r to any player who has joined, even offline, and §lSent§r (your last 30 letters, §esentLimit§r)"
      }
    ]
  },
  {
    "folder": "nick_bp",
    "topic": "nick",
    "name": "Nicknames",
    "summary": "Pick a nickname and a color to show above your head instead of your gamertag. Chat, the player list and death messages still show gamertags: the stable Script API can't change chat.",
    "steps": [
      {
        "text": "Run §e/realm:nick§r, type a nickname (3 to 16 letters A-Z, digits, spaces or §e_§r), pick a color and tap §lSave§r. It shows above your head right away, with your gamertag in gray underneath.",
        "ops": false
      },
      {
        "text": "Run §e/realm:nick§r again to change it, or enable §lRemove my nickname§r there to show your gamertag again. Your nickname stays when you leave, die or the realm restarts.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:nick§r -> §lPlayers' nicknames (operator)§r lists every saved nickname; tap one to clear it, even for players who are offline. To turn nicknames off for everyone, disable §lNicknames§r in §e/realm:config§r -> §lNicknames§r.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:nick",
        "ops": false,
        "who": "Everyone",
        "text": "Set, change or remove your nickname and its color, shown above your head (3 to 16 letters, digits, spaces or §e_§r). Operators also get every saved nickname, to clear any of them. Works while nicknames are enabled (default enabled, §eenabled§r)"
      }
    ]
  },
  {
    "folder": "quests_bp",
    "topic": "quests",
    "name": "Daily Quests",
    "summary": "Every player gets three quests a day, such as mining coal, defeating zombies, harvesting wheat or traveling 1,000 blocks, each with a reward of XP levels or items. New quests come at midnight UTC.",
    "steps": [
      {
        "text": "Play: about 10 seconds after you join, chat lists today's quests, for example §eNew daily quests: Mine 12 coal ore, Defeat 10 zombies, Travel 1,000 blocks.§r They count as you play; nothing to start.",
        "ops": false
      },
      {
        "text": "A note above the hotbar shows your progress at each quarter (§eQuest: Mine 12 coal ore 6/12§r). Finishing one says §eQuest complete: Mine 12 coal ore! Reward: 16 Torch§r in chat and gives the reward.",
        "ops": false
      },
      {
        "text": "Run §e/realm:quests§r to see today's quests with progress bars, their rewards and the time until new ones (§eNew quests in 5h 12m§r).",
        "ops": false
      },
      {
        "text": "Don't want the progress notes? Disable §lQuest progress notes§r in §e/realm:prefs§r.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:config§r -> §lDaily Quests§r sets the hour new quests come (UTC), how many each player gets, and whether creative mode counts. The quests themselves and their rewards are the §epool§r in §econfig.js§r.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:quests",
        "ops": false,
        "who": "Everyone",
        "text": "Shows today's quests (default 3, §equestsPerDay§r) with your progress and rewards, and the time until new ones (default midnight UTC, §eresetHourUtc§r)"
      }
    ]
  },
  {
    "folder": "milestones_bp",
    "topic": "milestones",
    "name": "Milestones",
    "summary": "Realm achievements in tiers: play 1, 10 and 100 hours, mine 1,000, 10,000 and 100,000 blocks, travel a million blocks and more. Unlocks are announced in chat, and anyone can look at anyone's progress.",
    "steps": [
      {
        "text": "Play: milestones count on their own. Reaching one tells everyone in chat, for example §eSam reached a milestone: Miner II (Mine 10,000 blocks)§r, with a sound.",
        "ops": false
      },
      {
        "text": "Run §e/realm:milestones§r to see yours: each milestone with the tier you have, a progress bar toward the next one and what it takes (§eMine 100,000 blocks§r).",
        "ops": false
      },
      {
        "text": "Pick §lAnother player's milestones§r to see anyone who has played since the pack was added, online or not.",
        "ops": false
      },
      {
        "text": "§lOperators:§r to keep unlocks out of public chat, disable §lAnnounce unlocks to everyone§r in §e/realm:config§r -> §lMilestones§r; then only the player is told. The milestones and their tiers are §emilestones§r in §econfig.js§r.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:milestones",
        "ops": false,
        "who": "Everyone",
        "text": "Shows your milestones with progress toward the next tier, and §lAnother player's milestones§r for anyone who has played since the pack was added. Unlocks are announced to everyone (default enabled, §eannounce§r)"
      }
    ]
  },
  {
    "folder": "goals_bp",
    "topic": "goals",
    "name": "Community Goals",
    "summary": "Shared goals for the whole realm, like 10,000 cobblestone for the Colosseum. Operators set the item, the amount and the chest it goes into; everyone donates from their inventory, and chat cheers each quarter of the way.",
    "steps": [
      {
        "text": "Run §e/realm:goals§r to see the realm's goals, each with how far along it is (§eColosseum: 23 percent§r, §e2,340 / 10,000 Cobblestone§r).",
        "ops": false
      },
      {
        "text": "Pick a goal, then §lDonate from my inventory§r: every matching item you carry (hotbar included) goes into the goal's chest, up to what the goal still needs. Chat says §eYou gave 320 Cobblestone to Colosseum.§r",
        "ops": false
      },
      {
        "text": "The goal's page shows a progress bar, where its chest is, what you gave and the top contributors.",
        "ops": false
      },
      {
        "text": "At 25, 50 and 75 percent everyone sees it in chat, and when a goal is reached chat thanks its top contributors.",
        "ops": false
      },
      {
        "text": "§lOperators:§r place a chest or barrel for the donations, look at it and run §e/realm:goals_add <item> <amount> [name]§r, for example §e/realm:goals_add cobblestone 10000 Colosseum§r. In a goal's page, §lMark finished§r stops donations early, §lLink to the block I'm looking at§r moves the goal to another container, and §lRemove this goal§r deletes it (the items stay in its chest).",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:goals",
        "ops": false,
        "who": "Everyone",
        "text": "Lists the community goals with their progress; pick one to donate from your inventory and see the top contributors (default 5, §etopContributors§r). Operators can mark a goal finished, move it to another container or remove it there"
      },
      {
        "usage": "/realm:goals_add <item> <amount> [name]",
        "ops": true,
        "who": "Ops",
        "text": "Adds a goal collected into the chest, barrel or other container you're looking at (within 8 blocks, §elinkDistance§r): §eitem§r is the item id, §eamount§r 1 to 1,000,000, §ename§r up to 32 characters (default: the item's name). Up to 30 goals at a time, finished ones included (§emaxGoals§r)"
      }
    ]
  },
  {
    "folder": "leaves_bp",
    "topic": "leaves",
    "name": "Fast Leaf Decay",
    "summary": "Chop a tree and its leaves fall within a few seconds instead of hanging in the air for minutes, dropping the usual saplings, sticks and apples. Leaves you placed yourself are never touched.",
    "steps": [
      {
        "text": "Chop down a tree as usual, log by log or all at once with a sneak-break (Bedrock Essentials+ tree felling).",
        "ops": false
      },
      {
        "text": "About a second after the last log breaks, the leaves that no longer reach a log start breaking on their own, a few at a time, with their normal drops. Pick up the saplings and apples underneath.",
        "ops": false
      },
      {
        "text": "Leaves still held by another tree's logs stay, as in vanilla. So do leaves you placed, sheared ones included.",
        "ops": false
      },
      {
        "text": "§lOperators:§r to go back to vanilla leaf decay, disable §lFast leaf decay§r in §e/realm:config§r -> §lFast Leaf Decay§r. The same page sets how many leaves break per tick.",
        "ops": true
      }
    ],
    "commands": []
  },
  {
    "folder": "cleanup_bp",
    "topic": "cleanup",
    "name": "Lag Cleanup",
    "summary": "When too many dropped items pile up (a broken farm, a big explosion), the realm warns everyone and clears them 30 seconds later, so the server doesn't lag. Renamed items, rare items and items right next to a player are kept.",
    "steps": [
      {
        "text": "Nothing to set up. If more than 500 dropped items (§ethreshold§r) lie around, chat says §eClearing 612 dropped items in 30 s: pick up what you need§r. Pick up anything you want to keep.",
        "ops": false
      },
      {
        "text": "30 seconds later they're removed, and chat says §eCleared 580 dropped items. (32 kept: renamed, rare or near a player)§r.",
        "ops": false
      },
      {
        "text": "Items renamed on an anvil, shulker boxes, elytra, nether stars, totems and the other items in §ekeepItems§r, and items within 4 blocks of a player (§enearPlayerRadius§r) are never cleared.",
        "ops": false
      },
      {
        "text": "Run §e/realm:cleanup§r to see how many dropped items there are in each dimension.",
        "ops": false
      },
      {
        "text": "§lOperators:§r §e/realm:cleanup§r opens a menu to clear now, clear after a warning, or call off a coming cleanup. Change the threshold, timing and what's kept in §e/realm:config§r -> §lLag Cleanup§r, or disable §lAutomatic cleanup§r there.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:cleanup",
        "ops": false,
        "who": "Everyone",
        "text": "Shows the dropped items in each dimension and when they're cleared (above 500, §ethreshold§r, counted every 60 s, §echeckSeconds§r). Operators get a menu to clear them now, clear after a 30 s warning (§ewarnSeconds§r) or call off a coming cleanup"
      }
    ]
  },
  {
    "folder": "chairs_bp",
    "topic": "chairs",
    "name": "Chairs",
    "summary": "Sit on any stair or bottom slab, which makes the furnished houses on mc.nish.software feel lived in.",
    "steps": [
      {
        "text": "Tap a stair or a bottom slab with an empty hand, standing within 2.5 blocks of it. You sit on it, facing away from the stair's back.",
        "ops": false
      },
      {
        "text": "Sneak to stand up (on touch screens, the dismount button). The bar above the hotbar reminds you when you sit.",
        "ops": false
      },
      {
        "text": "Run §e/realm:sit§r to sit down right where you stand.",
        "ops": false
      }
    ],
    "commands": [
      {
        "usage": "/realm:sit",
        "ops": false,
        "who": "Everyone",
        "text": "Sits you down where you stand (on the ground). Sneak to stand up"
      }
    ]
  },
  {
    "folder": "rain_bp",
    "topic": "rain",
    "name": "Rain Extras",
    "summary": "Storm fog, a darker rain haze on Vibrant Visuals, ground mist, drips under leaves and roof edges, the thunderstorm recording during storms, storm wind, rain on the roof and the rain muffled indoors, for the Realistic Rain resource pack. A §lstandalone§r behavior pack: it runs next to the Realm Bundle, not inside it.",
    "steps": [
      {
        "text": "When it rains, water drips from the leaves of trees and from roof edges near you, and keeps dripping for a while after the rain stops. Outdoors a soft breeze blows; indoors the rain sounds muffled through the roof, and drums on it.",
        "ops": false
      },
      {
        "text": "In a thunderstorm, the fog rolls in thicker and darker over about 12 seconds, the storm rumbles all around you with strong wind gusts (both muffled when you're inside), and low mist drifts along the ground with the wind when you're outdoors. It all clears the same way when the storm passes.",
        "ops": false
      },
      {
        "text": "On §lVibrant Visuals§r, rain also brings a darker blue-gray haze that settles in the valleys, since Vibrant Visuals ignores fog colors. Fancy keeps Realistic Rain's fog.",
        "ops": false
      },
      {
        "text": "Run §e/realm:rain§r, or use the same switch in §e/realm:prefs§r, to disable these extras for yourself, on a slower device for example. Chat says §eRain extras (fog, haze, mist, drips and sounds): Disabled. Run /realm:rain again to enable them.§r The choice is remembered.",
        "ops": false
      },
      {
        "text": "§lOperators:§r add Rain Extras under §lBehavior Packs§r, next to the Realm Bundle (it's never part of the bundle), and add Realistic Rain under §lResource Packs§r at the top of the list. The fogs, particles and sounds come from Realistic Rain, so without it nothing shows. §e/realm:config§r -> Rain Extras enables or disables each extra and sets the wind, thunderstorm and roof volumes.",
        "ops": true
      }
    ],
    "commands": [
      {
        "usage": "/realm:rain",
        "ops": false,
        "who": "Everyone",
        "text": "Enables or disables storm fog, haze, ground mist, drips, the wind, thunderstorm and roof sounds and the muffled rain indoors §lfor yourself§r (enabled by default, §edefaultOff§r). Remembered between sessions"
      }
    ]
  }
];
