// Generates packs/rain_rp/fogs/: denser, gloomier rain fog for the overworld, plus the storm fogs that
// Rain Extras pushes during thunderstorms.
//
// A pack's fog file replaces the vanilla definition with the same identifier wholesale, so each override is a
// verbatim copy of the vanilla file (tools/gen-rain/vanilla/fogs/) with only `distance.weather` changed.
// Fogs that don't define `weather` fall through to minecraft:fog_default, which is overridden here too.
//
//   node tools/gen-rain/fogs.mjs           write them
//   node tools/gen-rain/fogs.mjs --check   fail if the committed files differ, or an override changes more than the weather fog
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { isDeepStrictEqual } from "node:util";

const root = join(import.meta.dirname, "..", "..");
const vanillaDir = join(import.meta.dirname, "vanilla", "fogs");
const outDir = join(root, "packs", "rain_rp", "fogs");
const check = process.argv.includes("--check");

/** Rain fog, as fractions of the render distance (vanilla: 0.23 → 0.70, #666666). */
const RAIN = { start: 0.15, end: 0.55, color: "#5F6B79" };
/** Biome fogs that keep their own weather color (only the density changes). */
const KEEP_COLOR = new Set(["pale_garden_fog_setting.json", "sulfur_cave_fog_setting.json"]);
/** Thunderstorm fogs, pushed per player by Rain Extras with /fog in three steps so the fog rolls in. */
const STORM = [
  { file: "rain_storm_1.json", id: "realm:rain_storm_1", start: 0.12, end: 0.48, color: "#59646F" },
  { file: "rain_storm_2.json", id: "realm:rain_storm_2", start: 0.1, end: 0.41, color: "#545D69" },
  { file: "rain_storm.json", id: "realm:rain_storm", start: 0.08, end: 0.35, color: "#4E5763" },
];

/** Rewrites the numbers in the "weather" block of a fog file's text, keeping Mojang's formatting. */
function patchWeather(/** @type {string} */ text, /** @type {string} */ name) {
  const block = /("weather"\s*:\s*\{)([^{}]*)(\})/;
  const m = text.match(block);
  if (!m) throw new Error(`${name}: no "weather" block`);
  let body = m[2]
    .replace(/("fog_start"\s*:\s*)[\d.]+/, `$1${RAIN.start}`)
    .replace(/("fog_end"\s*:\s*)[\d.]+/, `$1${RAIN.end}`);
  if (!KEEP_COLOR.has(name)) body = body.replace(/("fog_color"\s*:\s*)"#[0-9A-Fa-f]{6}"/, `$1"${RAIN.color}"`);
  return text.replace(block, `$1${body}$3`);
}

function storm(/** @type {typeof STORM[number]} */ s) {
  const fog = {
    format_version: "1.16.100",
    "minecraft:fog_settings": {
      description: { identifier: s.id },
      // Only the weather fog: in clear weather, underwater or in the Nether a leftover push changes nothing.
      distance: { weather: { fog_start: s.start, fog_end: s.end, fog_color: s.color, render_distance_type: "render" } },
    },
  };
  return JSON.stringify(fog, null, 2) + "\n";
}

/** @type {Map<string, string>} file name → contents */
const files = new Map();
const problems = [];
for (const name of readdirSync(vanillaDir).sort()) {
  const vanillaText = readFileSync(join(vanillaDir, name), "utf8");
  const text = patchWeather(vanillaText, name);
  // Guard: nothing but distance.weather may differ from vanilla.
  const a = JSON.parse(vanillaText), b = JSON.parse(text);
  const w = b["minecraft:fog_settings"].distance.weather;
  delete a["minecraft:fog_settings"].distance.weather;
  delete b["minecraft:fog_settings"].distance.weather;
  if (!isDeepStrictEqual(a, b)) problems.push(`${name}: changes more than distance.weather`);
  if (w.fog_start !== RAIN.start || w.fog_end !== RAIN.end || w.render_distance_type !== "render") problems.push(`${name}: weather fog not patched`);
  files.set(name, text);
}
for (const s of STORM) files.set(s.file, storm(s));

if (check) {
  const expected = new Set(files.keys());
  for (const [name, text] of files) {
    const file = join(outDir, name);
    if (!existsSync(file) || readFileSync(file, "utf8") !== text) problems.push(`${name}: out of date (run npm run gen:rain)`);
  }
  if (existsSync(outDir)) for (const name of readdirSync(outDir)) if (!expected.has(name)) problems.push(`${name}: not generated by fogs.mjs`);
  if (problems.length) {
    console.error(`rain_rp fogs:\n${problems.map((p) => `  - ${p}`).join("\n")}`);
    process.exit(1);
  }
  console.log(`rain_rp fogs match tools/gen-rain/fogs.mjs (${files.size} files).`);
} else {
  if (problems.length) throw new Error(problems.join("\n"));
  mkdirSync(outDir, { recursive: true });
  for (const [name, text] of files) writeFileSync(join(outDir, name), text);
  console.log(`wrote ${files.size} fogs to ${relative(root, outDir)}`);
}
