// Writes packs/help_bp/scripts/catalog.js, the in-game /realm:help text, from docs/PACKS.md: each pack's
// summary, "### How to use" steps and "### Commands" table. The docs are the one source, so the help
// can't drift from them. Also checks that every pack answers /realm:help's ping. Resource packs are left
// out: they have no script to answer the ping, so /realm:help could never list them.
//
//   node tools/help-catalog.mjs           write the catalog (and bump help_bp's patch version once)
//   node tools/help-catalog.mjs --check   fail if the catalog is out of date or a pack doesn't answer
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const HELP = "help_bp";
const out = join(root, "packs", HELP, "scripts", "catalog.js");
const manifestPath = join(root, "packs", HELP, "manifest.json");
const check = process.argv.includes("--check");

/** Markdown inline → Minecraft formatting codes: `code` yellow, **bold** bold, links as their text. */
function mc(/** @type {string} */ md) {
  return md
    .replaceAll("§", "&") // a literal section sign would start a formatting code in game
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/`([^`]+)`/g, "§e$1§r")
    .replace(/\*\*(.+?)\*\*/g, "§l$1§r")
    .replace(/\\\|/g, "|")
    .trim();
}

/** Lines of the `### title` subsection of a pack section. */
function subsection(/** @type {string[]} */ lines, /** @type {string} */ title) {
  const start = lines.findIndex((l) => l.trim() === `### ${title}`);
  if (start < 0) return [];
  const end = lines.findIndex((l, i) => i > start && (/^#{2,3} /.test(l) || l.trim() === "---"));
  return lines.slice(start + 1, end < 0 ? undefined : end);
}

/** Numbered steps, with indented "- " bullets and continuation lines folded into their step. */
function steps(/** @type {string[]} */ lines) {
  /** @type {{ text: string, ops: boolean }[]} */
  const out = [];
  for (const line of lines) {
    const step = line.match(/^\d+\.\s+(.*)$/);
    const bullet = line.match(/^\s+[-*]\s+(.*)$/);
    if (step) out.push({ text: mc(step[1]), ops: /^\*\*Operators\b/.test(step[1]) });
    else if (bullet && out.length) out.at(-1).text += `\n  • ${mc(bullet[1])}`;
    else if (line.trim() && out.length) out.at(-1).text += ` ${mc(line)}`;
  }
  return out;
}

/** Rows of the Commands table: usage, who, what it does. */
function commands(/** @type {string[]} */ lines) {
  const rows = lines.filter((l) => l.startsWith("|")).slice(2); // header and separator rows
  return rows.map((row) => {
    const cells = row.slice(1, -1).split(/(?<!\\)\|/).map((c) => c.trim());
    const usage = cells[0].replace(/`/g, "");
    return { usage, ops: /^ops\b/i.test(cells[1]), who: mc(cells[1]), text: mc(cells[2]) };
  });
}

/** A resource pack has no scripts, so it can't answer the ping. */
function isResourcePack(/** @type {string} */ folder) {
  const manifest = join(root, "packs", folder, "manifest.json");
  return existsSync(manifest) && JSON.parse(readFileSync(manifest, "utf8")).modules.some((/** @type {any} */ m) => m.type === "resources");
}

const docs = readFileSync(join(root, "docs", "PACKS.md"), "utf8").split("\n");
const packs = [];
for (let i = 0; i < docs.length; i++) {
  const head = docs[i].match(/^## (.+?) — `(\w+)`\s*$/);
  if (!head || isResourcePack(head[2])) continue;
  const end = docs.findIndex((l, j) => j > i && l.startsWith("## "));
  const lines = docs.slice(i + 1, end < 0 ? undefined : end);
  const first = lines.findIndex((l) => l.trim());
  const blank = lines.findIndex((l, j) => j > first && !l.trim());
  packs.push({
    folder: head[2],
    topic: head[2].replace(/_bp$/, ""),
    name: head[1],
    summary: mc(lines.slice(first, blank < 0 ? undefined : blank).join(" ")),
    steps: steps(subsection(lines, "How to use")),
    commands: commands(subsection(lines, "Commands")),
  });
}

const text =
  "// Generated by tools/help-catalog.mjs from docs/PACKS.md. Don't edit: change the docs, then run it again.\n" +
  `export const PACKS = ${JSON.stringify(packs, null, 2)};\n`;

const problems = [];
// Every other pack must answer the ping, or /realm:help never lists it.
for (const folder of readdirSync(join(root, "packs"))) {
  const main = join(root, "packs", folder, "scripts", "main.js");
  if (folder === HELP || !existsSync(main)) continue;
  const src = readFileSync(main, "utf8");
  if (!src.includes('"realm:help_ping"') || !src.includes(`"realm:help_pong", "${folder}"`)) {
    problems.push(`${folder}: doesn't answer /realm:help (subscribe to "realm:help_ping", reply "realm:help_pong" with "${folder}")`);
  }
}
const current = existsSync(out) ? readFileSync(out, "utf8") : "";

if (check) {
  if (current !== text) problems.push(`${HELP}: scripts/catalog.js is out of date with docs/PACKS.md (run node tools/help-catalog.mjs)`);
  if (problems.length) {
    console.error(`/realm:help problems:\n${problems.map((p) => `  - ${p}`).join("\n")}`);
    process.exit(1);
  }
  console.log(`/realm:help catalog matches docs/PACKS.md (${packs.length} packs) and every pack answers.`);
} else {
  if (problems.length) console.warn(problems.map((p) => `warning: ${p}`).join("\n"));
  if (current === text) {
    console.log("catalog.js already up to date.");
  } else {
    writeFileSync(out, text);
    // A changed catalog is a changed pack: bump the patch version once per commit.
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    let committed;
    try {
      committed = JSON.parse(execFileSync("git", ["show", `HEAD:packs/${HELP}/manifest.json`], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] })).header.version;
    } catch {
      committed = undefined; // new pack or no git: leave the version alone
    }
    if (committed && committed.join(".") === manifest.header.version.join(".")) {
      const [x, y, z] = manifest.header.version;
      // Edit the text, not a re-serialized object, so the manifest keeps its formatting.
      const raw = readFileSync(manifestPath, "utf8");
      writeFileSync(manifestPath, raw.replace(`"version": [${x}, ${y}, ${z}],\n    "min_engine_version"`, `"version": [${x}, ${y}, ${z + 1}],\n    "min_engine_version"`));
      console.log(`wrote ${out.replace(root + "/", "")}; ${HELP} is now ${x}.${y}.${z + 1}`);
    } else {
      console.log(`wrote ${out.replace(root + "/", "")}`);
    }
  }
}
